apiVersion: v1
kind: ServiceAccount
metadata:
  name: chess-tournament-app
  namespace: chess-tournament
  annotations:
    # For Workload Identity - link to GCP service account
    iam.gke.io/gcp-service-account: gke-nodes-SUFFIX@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: chess-tournament
