apiVersion: v1
kind: Service
metadata:
  name: chess-tournament-service
  namespace: chess-tournament
  labels:
    app: chess-tournament
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: chess-tournament
    component: web
